feature/frontend:
  - changed-files:
    - any-glob-to-any-file: 'src/app/**'
    - any-glob-to-any-file: 'src/components/**'
    - any-glob-to-any-file: 'src/styles/**'
    - any-glob-to-any-file: 'public/**'

feature/backend:
  - changed-files:
    - any-glob-to-any-file: 'src/app/api/**'
    - any-glob-to-any-file: 'src/lib/**'
    - any-glob-to-any-file: 'src/services/**'
    - any-glob-to-any-file: 'src/types/**'
    - any-glob-to-any-file: 'prisma/**'

chore/config:
  - changed-files:
    - any-glob-to-any-file: '.github/**'
    - any-glob-to-any-file: 'package.json'
    - any-glob-to-any-file: 'next.config.*'
    - any-glob-to-any-file: 'tsconfig.json'
    - any-glob-to-any-file: 'tailwind.config.*'

project/docs:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
    - any-glob-to-any-file: 'README.md'
    - any-glob-to-any-file: '**/*.md'
